name: Android CI
on: [workflow_dispatch, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          cache: 'gradle'

      - run: chmod +x gradlew

      - name: Build with debug info
        run: |
          ./gradlew assembleRelease \
            --no-daemon \
            --stacktrace \
            --info || exit 1  # 明确失败时退出

      - name: List build outputs  # 调试用
        run: find app/build/outputs -name "*.apk"

      - uses: actions/upload-artifact@v4
        if: success()  # 仅在之前步骤成功时运行
        with:
          name: app-release
          path: app/build/outputs/apk/**/*.apk
          retention-days: 3
