name: Build Android APK
on:
  push:
    branches: [ main ]  # 只在 main 分支推送时触发
  pull_request:
    branches: [ main ]  # 也可在 PR 时触发

jobs:
  build:
    runs-on: ubuntu-latest  # 使用 GitHub 提供的 Ubuntu 虚拟机
    steps:
      # 1. 拉取代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 设置 JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'  # 使用 Eclipse Temurin JDK

      # 3. 构建 APK（Release 版）
      - name: Build Release APK
        run: |
          chmod +x gradlew
          ./gradlew assembleRelease

      # 4. 上传 APK 作为构建产物（Artifact）
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: app/build/outputs/apk/release/
